### PR TITLE
Remove unnecessary `convert_dataframe_to_pandas_numpy` call after `interchange_to_pandas` call

### PR DESCRIPTION
**Pull request by anmyachev**
`interchange_to_pandas` uses `convert_dataframe_to_pandas_numpy` internally in all cases.

### CODE REVIEW

**Comment by anmyachev** [comment]
Hi @MarcoGorelli! Could you take a look?

**Review by MarcoGorelli — APPROVED** [review]
thanks @anmyachev , looks like I forgot to clean this up

ideally I think we shouldn't be interchanging to pandas at all for the test suite, and should develop some dataframe-agnostic testing functionality

**Comment by anmyachev** [comment]
> ideally I think we shouldn't be interchanging to pandas at all for the test suite, and should develop some dataframe-agnostic testing functionality

Considering that dataframes cannot be compared with each other, some kind of universal representation is needed. I can try to take the result of `to_array` function as such a representation and compare it with a manually constructed NumPy array.

**Comment by MarcoGorelli** [comment]
I was thinking of something like
```python
assert result.col('a').take(0) == x
assert result.col('a').take(1) == y
assert result.col('a').take(2) == z
```

**Comment by anmyachev** [comment]
> I was thinking of something like
> 
> ```python
> assert result.col('a').take(0) == x
> assert result.col('a').take(1) == y
> assert result.col('a').take(2) == z
> ```

Your option is as universal as possible and will allow third-party libraries not to install NumPy as a dependency. However, in this case, the ability to vectorize comparisons is lost (which is probably not a problem for small data) and we may have to implement some of our own comparison mechanisms, such as absolute and relative tolerance for floats.

**Pull request merged**
